# Generated by Django 3.1.2 on 2021-01-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Author_Paper',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='Keyword_Paper',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
